# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command(
  'node',
  ['-p',
   'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]
).strip

ENV['RCT_NEW_ARCH_ENABLED'] = '1'

platform :ios, min_ios_version_supported
prepare_react_native_project!

target 'BookMeLoanAppReact' do

  use_modular_headers!
  use_frameworks! :linkage => :static

  $RNFirebaseAsStaticFramework = true

  # Firebase modular header fixes
  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true
  pod 'FirebaseCoreInternal', :modular_headers => true

  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :hermes_enabled => false
  )

  post_install do |installer|

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |build_config|
  
        build_config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
  
        build_config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
          '$(inherited)'
        ]
  
        # Fix missing Hermes dSYM during archive
        build_config.build_settings['DEBUG_INFORMATION_FORMAT'] = 'dwarf-with-dsym'
  
        if target.name == 'fmt'
  
          # Fix Xcode 16/26 fmt consteval crash
          build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++17'
  
          build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] ||= [
            '$(inherited)'
          ]
  
          build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DFMT_USE_CONSTEVAL=0'
          build_config.build_settings['OTHER_CPLUSPLUSFLAGS'] << '-DFMT_USE_CONSTEXPR=0'
  
        else
  
          build_config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'gnu++20'
  
        end
  
      end
    end
  
    # Prevent Hermes symbols from being stripped
    installer.aggregate_targets.each do |aggregate_target|
      aggregate_target.user_project.native_targets.each do |target|
        target.build_configurations.each do |config|
  
          config.build_settings['STRIP_INSTALLED_PRODUCT'] = 'NO'
  
        end
      end
    end
  
  end
end